"""Pydantic data models for the trading bot.

Every data structure that flows through the system — candles, signals, orders,
positions, trades, portfolio state, and agent opinions — is defined here as a
validated Pydantic model.
"""

from __future__ import annotations

from datetime import datetime, timedelta
from typing import Any, Optional
from uuid import uuid4

from pydantic import BaseModel, ConfigDict, Field, computed_field

from .enums import (
    AgentRole,
    Exchange,
    OrderStatus,
    OrderType,
    PositionType,
    Side,
    SignalAction,
    TimeFrame,
)


# ── Market Data ──────────────────────────────────────────────────────────────


class Candle(BaseModel):
    """OHLCV candle for a single instrument and timeframe."""

    model_config = ConfigDict(frozen=True)

    symbol: str
    exchange: Exchange = Exchange.NSE
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: int
    timeframe: TimeFrame = TimeFrame.M5


class IndicatorValues(BaseModel):
    """Computed technical indicator values for a point in time.

    All fields are Optional because not every indicator is computable on
    every candle (e.g., SMA-50 needs 50 candles of history).
    """

    # Moving Averages
    sma_20: Optional[float] = None
    sma_50: Optional[float] = None
    sma_200: Optional[float] = None
    ema_9: Optional[float] = None
    ema_21: Optional[float] = None

    # Momentum
    rsi_14: Optional[float] = None
    macd: Optional[float] = None
    macd_signal: Optional[float] = None
    macd_histogram: Optional[float] = None
    adx: Optional[float] = None
    cci_20: Optional[float] = None

    # Volatility
    bb_upper: Optional[float] = None
    bb_middle: Optional[float] = None
    bb_lower: Optional[float] = None
    atr_14: Optional[float] = None

    # Volume
    vwap: Optional[float] = None
    volume_sma_20: Optional[float] = None
    obv: Optional[float] = None

    # Trend
    supertrend: Optional[float] = None
    supertrend_direction: Optional[int] = None  # 1 = bullish, -1 = bearish


# ── Signals & Decisions ──────────────────────────────────────────────────────


class Signal(BaseModel):
    """A trading signal generated by a strategy or agent."""

    id: str = Field(default_factory=lambda: str(uuid4()))
    symbol: str
    exchange: Exchange = Exchange.NSE
    action: SignalAction
    confidence: float = Field(ge=0.0, le=1.0, description="0.0 = no confidence, 1.0 = max")
    entry_price: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    quantity: Optional[int] = None
    reasoning: str = ""
    source_agent: AgentRole = AgentRole.PORTFOLIO_MANAGER
    timestamp: datetime = Field(default_factory=datetime.now)
    metadata: dict[str, Any] = Field(default_factory=dict)


class AgentOpinion(BaseModel):
    """An individual agent's opinion during the decision pipeline."""

    agent_role: AgentRole
    action: SignalAction
    confidence: float = Field(ge=0.0, le=1.0)
    reasoning: str
    key_factors: list[str] = Field(default_factory=list)
    timestamp: datetime = Field(default_factory=datetime.now)


class TechnicalOpinion(BaseModel):
    """Structured opinion from the Technical Analyst agent."""

    action: SignalAction
    confidence: float = Field(ge=0.0, le=1.0)
    support_level: Optional[float] = None
    resistance_level: Optional[float] = None
    trend_strength: str = "NEUTRAL"
    reasoning: str = ""


class SentimentOpinion(BaseModel):
    """Structured opinion from the Sentiment Analyst agent."""

    company_sentiment: float = Field(ge=-1.0, le=1.0, default=0.0)
    sector_sentiment: float = Field(ge=-1.0, le=1.0, default=0.0)
    macro_sentiment: float = Field(ge=-1.0, le=1.0, default=0.0)
    overall_action: SignalAction = SignalAction.HOLD
    overall_confidence: float = Field(ge=0.0, le=1.0, default=0.5)
    top_headlines: list[str] = Field(default_factory=list)
    reasoning: str = ""


class BullOpinion(BaseModel):
    """Structured thesis from the Bull agent."""

    bull_score: float = Field(ge=0.0, le=1.0)
    target_price: Optional[float] = None
    thesis_summary: str = ""


class BearOpinion(BaseModel):
    """Structured thesis from the Bear agent."""

    bear_score: float = Field(ge=0.0, le=1.0)
    invalidation_price: Optional[float] = None
    thesis_summary: str = ""


class PortfolioProposal(BaseModel):
    """Proposal generated by Portfolio Manager before Risk Manager Veto."""

    symbol: str
    proposed_action: SignalAction
    confidence: float = Field(ge=0.0, le=1.0)
    entry_price: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    position_size_pct: float = Field(ge=0.0, le=100.0, default=1.0)
    rationale: str = ""


class RiskVeto(BaseModel):
    """Risk Manager hard veto output."""

    approve: bool
    allowed_position_size: int = 0
    veto_reason: str = ""


class TradingDecision(BaseModel):
    """Final trading decision produced by the agent orchestrator."""

    symbol: str
    action: SignalAction
    confidence: float = Field(ge=0.0, le=1.0)
    entry_price: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    position_size: Optional[int] = None
    reasoning: str = ""
    agent_opinions: list[AgentOpinion] = Field(default_factory=list)
    approved_by_risk: bool = False
    veto_reason: Optional[str] = None
    timestamp: datetime = Field(default_factory=datetime.now)


# ── Orders ───────────────────────────────────────────────────────────────────


class OrderFees(BaseModel):
    """Breakdown of fees for a single order (Indian market structure)."""

    brokerage: float = 0.0
    stt: float = 0.0              # Securities Transaction Tax
    exchange_charges: float = 0.0
    gst: float = 0.0
    sebi_charges: float = 0.0
    stamp_duty: float = 0.0

    @computed_field  # type: ignore[prop-decorator]
    @property
    def total(self) -> float:
        return (
            self.brokerage
            + self.stt
            + self.exchange_charges
            + self.gst
            + self.sebi_charges
            + self.stamp_duty
        )


class Order(BaseModel):
    """A single order (pending, filled, or cancelled)."""

    id: str = Field(default_factory=lambda: str(uuid4()))
    symbol: str
    exchange: Exchange = Exchange.NSE
    side: Side
    order_type: OrderType = OrderType.MARKET
    quantity: int
    price: Optional[float] = None          # limit price
    trigger_price: Optional[float] = None  # stop-loss trigger
    status: OrderStatus = OrderStatus.PENDING
    filled_quantity: int = 0
    average_price: float = 0.0
    position_type: PositionType = PositionType.DELIVERY

    # Linkage
    signal_id: Optional[str] = None
    parent_order_id: Optional[str] = None  # for bracket / cover orders

    # Fees
    fees: OrderFees = Field(default_factory=OrderFees)

    # Timestamps
    created_at: datetime = Field(default_factory=datetime.now)
    filled_at: Optional[datetime] = None
    cancelled_at: Optional[datetime] = None

    @computed_field  # type: ignore[prop-decorator]
    @property
    def is_terminal(self) -> bool:
        """Whether this order is in a final state."""
        return self.status in (
            OrderStatus.FILLED,
            OrderStatus.CANCELLED,
            OrderStatus.REJECTED,
        )


# ── Positions & Trades ───────────────────────────────────────────────────────


class Position(BaseModel):
    """An open position in a single instrument."""

    id: str = Field(default_factory=lambda: str(uuid4()))
    symbol: str
    exchange: Exchange = Exchange.NSE
    side: Side
    quantity: int
    entry_price: float
    current_price: float = 0.0
    position_type: PositionType = PositionType.DELIVERY

    # Risk levels
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    trailing_stop: Optional[float] = None

    # Linkage
    entry_order_id: str = ""
    signal_id: Optional[str] = None
    entry_time: datetime = Field(default_factory=datetime.now)

    @computed_field  # type: ignore[prop-decorator]
    @property
    def unrealized_pnl(self) -> float:
        """Unrealized P&L in absolute rupees."""
        multiplier = 1 if self.side == Side.BUY else -1
        return multiplier * (self.current_price - self.entry_price) * self.quantity

    @computed_field  # type: ignore[prop-decorator]
    @property
    def unrealized_pnl_pct(self) -> float:
        """Unrealized P&L as a percentage of entry value."""
        if self.entry_price == 0:
            return 0.0
        return (self.unrealized_pnl / (self.entry_price * self.quantity)) * 100

    def should_stop_loss(self) -> bool:
        """Check if current price has breached the stop loss."""
        if self.stop_loss is None:
            return False
        if self.side == Side.BUY:
            return self.current_price <= self.stop_loss
        return self.current_price >= self.stop_loss

    def should_take_profit(self) -> bool:
        """Check if current price has breached the take profit."""
        if self.take_profit is None:
            return False
        if self.side == Side.BUY:
            return self.current_price >= self.take_profit
        return self.current_price <= self.take_profit


class Trade(BaseModel):
    """A completed trade (entry → exit) with realized P&L."""

    id: str = Field(default_factory=lambda: str(uuid4()))
    symbol: str
    exchange: Exchange = Exchange.NSE
    side: Side  # side of the entry
    quantity: int
    entry_price: float
    exit_price: float
    entry_time: datetime
    exit_time: datetime

    gross_pnl: float = 0.0
    total_fees: float = 0.0
    net_pnl: float = 0.0

    entry_order_id: str = ""
    exit_order_id: str = ""
    signal_id: Optional[str] = None

    @computed_field  # type: ignore[prop-decorator]
    @property
    def holding_period(self) -> timedelta:
        return self.exit_time - self.entry_time

    @computed_field  # type: ignore[prop-decorator]
    @property
    def pnl_pct(self) -> float:
        """Net P&L as percentage of entry value."""
        if self.entry_price == 0:
            return 0.0
        multiplier = 1 if self.side == Side.BUY else -1
        return multiplier * ((self.exit_price - self.entry_price) / self.entry_price) * 100

    @computed_field  # type: ignore[prop-decorator]
    @property
    def is_winner(self) -> bool:
        return self.net_pnl > 0


# ── Portfolio ────────────────────────────────────────────────────────────────


class PortfolioState(BaseModel):
    """Snapshot of the full portfolio at a point in time."""

    initial_capital: float
    current_capital: float  # cash available (excludes margin in positions)
    positions: list[Position] = Field(default_factory=list)
    completed_trades: list[Trade] = Field(default_factory=list)

    # Running metrics
    daily_pnl: float = 0.0
    total_realized_pnl: float = 0.0
    peak_equity: float = 0.0
    max_drawdown: float = 0.0
    max_drawdown_pct: float = 0.0

    @computed_field  # type: ignore[prop-decorator]
    @property
    def total_unrealized_pnl(self) -> float:
        return sum(p.unrealized_pnl for p in self.positions)

    @computed_field  # type: ignore[prop-decorator]
    @property
    def equity(self) -> float:
        """Total equity = cash + unrealized P&L."""
        return self.current_capital + self.total_unrealized_pnl

    @computed_field  # type: ignore[prop-decorator]
    @property
    def open_position_count(self) -> int:
        return len(self.positions)

    @computed_field  # type: ignore[prop-decorator]
    @property
    def win_rate(self) -> float:
        """Win rate of completed trades."""
        if not self.completed_trades:
            return 0.0
        winners = sum(1 for t in self.completed_trades if t.is_winner)
        return (winners / len(self.completed_trades)) * 100

    def update_drawdown(self) -> None:
        """Recalculate peak equity and max drawdown."""
        current_equity = self.equity
        if current_equity > self.peak_equity:
            self.peak_equity = current_equity
        if self.peak_equity > 0:
            drawdown = self.peak_equity - current_equity
            drawdown_pct = (drawdown / self.peak_equity) * 100
            if drawdown > self.max_drawdown:
                self.max_drawdown = drawdown
                self.max_drawdown_pct = drawdown_pct


# ── Agent Context ────────────────────────────────────────────────────────────


class MarketContext(BaseModel):
    """All the data an agent needs to make a decision.

    This is passed through the LangGraph state and given to each agent
    as grounded, verified market data (RAG — no hallucinated prices).
    """

    symbol: str
    exchange: Exchange = Exchange.NSE
    current_price: float
    candles: list[Candle] = Field(default_factory=list)
    indicators: Optional[IndicatorValues] = None
    portfolio: Optional[PortfolioState] = None
    news_summary: Optional[str] = None
    timestamp: datetime = Field(default_factory=datetime.now)

    # India VIX regime data (populated by orchestrator/live feed)
    vix_data: Optional[dict[str, Any]] = None

    # NIFTY 50 benchmark data for alpha calculation: {"entry_price": float, "current_price": float}
    benchmark_data: Optional[dict[str, float]] = None
